/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerAuditRouteImport } from './routes/career-audit'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as InternshipPassportRouteImport } from './routes/internship-passport'
import { Route as InternshipXrayRouteImport } from './routes/internship-xray'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResumeIntelligenceRouteImport } from './routes/resume-intelligence'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TnpRouteImport } from './routes/tnp'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentCareerAuditRouteImport } from './routes/student.career-audit'
import { Route as StudentOpportunitiesRouteImport } from './routes/student.opportunities'
import { Route as StudentPassportRouteImport } from './routes/student.passport'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentResumeRouteImport } from './routes/student.resume'
import { Route as StudentXrayRouteImport } from './routes/student.xray'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAuditRoute = CareerAuditRouteImport.update({
  id: '/career-audit',
  path: '/career-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipPassportRoute = InternshipPassportRouteImport.update({
  id: '/internship-passport',
  path: '/internship-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipXrayRoute = InternshipXrayRouteImport.update({
  id: '/internship-xray',
  path: '/internship-xray',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeIntelligenceRoute = ResumeIntelligenceRouteImport.update({
  id: '/resume-intelligence',
  path: '/resume-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TnpRoute = TnpRouteImport.update({
  id: '/tnp',
  path: '/tnp',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCareerAuditRoute = StudentCareerAuditRouteImport.update({
  id: '/career-audit',
  path: '/career-audit',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOpportunitiesRoute = StudentOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPassportRoute = StudentPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResumeRoute = StudentResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => StudentRoute,
} as any)
const StudentXrayRoute = StudentXrayRouteImport.update({
  id: '/xray',
  path: '/xray',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career-audit': typeof CareerAuditRoute
  '/company': typeof CompanyRoute
  '/faculty': typeof FacultyRoute
  '/internship-passport': typeof InternshipPassportRoute
  '/internship-xray': typeof InternshipXrayRoute
  '/profile': typeof ProfileRoute
  '/resume-intelligence': typeof ResumeIntelligenceRoute
  '/student': typeof StudentRouteWithChildren
  '/tnp': typeof TnpRoute
  '/student/career-audit': typeof StudentCareerAuditRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/xray': typeof StudentXrayRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career-audit': typeof CareerAuditRoute
  '/company': typeof CompanyRoute
  '/faculty': typeof FacultyRoute
  '/internship-passport': typeof InternshipPassportRoute
  '/internship-xray': typeof InternshipXrayRoute
  '/profile': typeof ProfileRoute
  '/resume-intelligence': typeof ResumeIntelligenceRoute
  '/tnp': typeof TnpRoute
  '/student/career-audit': typeof StudentCareerAuditRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/xray': typeof StudentXrayRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career-audit': typeof CareerAuditRoute
  '/company': typeof CompanyRoute
  '/faculty': typeof FacultyRoute
  '/internship-passport': typeof InternshipPassportRoute
  '/internship-xray': typeof InternshipXrayRoute
  '/profile': typeof ProfileRoute
  '/resume-intelligence': typeof ResumeIntelligenceRoute
  '/student': typeof StudentRouteWithChildren
  '/tnp': typeof TnpRoute
  '/student/career-audit': typeof StudentCareerAuditRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/xray': typeof StudentXrayRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career-audit'
    | '/company'
    | '/faculty'
    | '/internship-passport'
    | '/internship-xray'
    | '/profile'
    | '/resume-intelligence'
    | '/student'
    | '/tnp'
    | '/student/career-audit'
    | '/student/opportunities'
    | '/student/passport'
    | '/student/profile'
    | '/student/resume'
    | '/student/xray'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career-audit'
    | '/company'
    | '/faculty'
    | '/internship-passport'
    | '/internship-xray'
    | '/profile'
    | '/resume-intelligence'
    | '/tnp'
    | '/student/career-audit'
    | '/student/opportunities'
    | '/student/passport'
    | '/student/profile'
    | '/student/resume'
    | '/student/xray'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/career-audit'
    | '/company'
    | '/faculty'
    | '/internship-passport'
    | '/internship-xray'
    | '/profile'
    | '/resume-intelligence'
    | '/student'
    | '/tnp'
    | '/student/career-audit'
    | '/student/opportunities'
    | '/student/passport'
    | '/student/profile'
    | '/student/resume'
    | '/student/xray'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerAuditRoute: typeof CareerAuditRoute
  CompanyRoute: typeof CompanyRoute
  FacultyRoute: typeof FacultyRoute
  InternshipPassportRoute: typeof InternshipPassportRoute
  InternshipXrayRoute: typeof InternshipXrayRoute
  ProfileRoute: typeof ProfileRoute
  ResumeIntelligenceRoute: typeof ResumeIntelligenceRoute
  StudentRoute: typeof StudentRouteWithChildren
  TnpRoute: typeof TnpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-audit': {
      id: '/career-audit'
      path: '/career-audit'
      fullPath: '/career-audit'
      preLoaderRoute: typeof CareerAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship-passport': {
      id: '/internship-passport'
      path: '/internship-passport'
      fullPath: '/internship-passport'
      preLoaderRoute: typeof InternshipPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship-xray': {
      id: '/internship-xray'
      path: '/internship-xray'
      fullPath: '/internship-xray'
      preLoaderRoute: typeof InternshipXrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-intelligence': {
      id: '/resume-intelligence'
      path: '/resume-intelligence'
      fullPath: '/resume-intelligence'
      preLoaderRoute: typeof ResumeIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tnp': {
      id: '/tnp'
      path: '/tnp'
      fullPath: '/tnp'
      preLoaderRoute: typeof TnpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/career-audit': {
      id: '/student/career-audit'
      path: '/career-audit'
      fullPath: '/student/career-audit'
      preLoaderRoute: typeof StudentCareerAuditRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/opportunities': {
      id: '/student/opportunities'
      path: '/opportunities'
      fullPath: '/student/opportunities'
      preLoaderRoute: typeof StudentOpportunitiesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/passport': {
      id: '/student/passport'
      path: '/passport'
      fullPath: '/student/passport'
      preLoaderRoute: typeof StudentPassportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/resume': {
      id: '/student/resume'
      path: '/resume'
      fullPath: '/student/resume'
      preLoaderRoute: typeof StudentResumeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/xray': {
      id: '/student/xray'
      path: '/xray'
      fullPath: '/student/xray'
      preLoaderRoute: typeof StudentXrayRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentCareerAuditRoute: typeof StudentCareerAuditRoute
  StudentOpportunitiesRoute: typeof StudentOpportunitiesRoute
  StudentPassportRoute: typeof StudentPassportRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResumeRoute: typeof StudentResumeRoute
  StudentXrayRoute: typeof StudentXrayRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCareerAuditRoute: StudentCareerAuditRoute,
  StudentOpportunitiesRoute: StudentOpportunitiesRoute,
  StudentPassportRoute: StudentPassportRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResumeRoute: StudentResumeRoute,
  StudentXrayRoute: StudentXrayRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerAuditRoute: CareerAuditRoute,
  CompanyRoute: CompanyRoute,
  FacultyRoute: FacultyRoute,
  InternshipPassportRoute: InternshipPassportRoute,
  InternshipXrayRoute: InternshipXrayRoute,
  ProfileRoute: ProfileRoute,
  ResumeIntelligenceRoute: ResumeIntelligenceRoute,
  StudentRoute: StudentRouteWithChildren,
  TnpRoute: TnpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
